platform :ios, '8.0'

use_frameworks!

target 'tpg offline' do
	pod 'SwiftyJSON', git: "https://github.com/SwiftyJSON/SwiftyJSON.git"
	pod 'ChameleonFramework' , git: "https://github.com/ViccAlexander/Chameleon.git"
	pod 'FontAwesomeKit', git: "https://github.com/PrideChung/FontAwesomeKit.git"
	pod 'SwiftLocation', git: "https://github.com/malcommac/SwiftLocation.git"
	pod 'BGTableViewRowActionWithImage', git: "https://github.com/benguild/BGTableViewRowActionWithImage.git"
	pod 'SCLAlertView', git: "https://github.com/vikmeup/SCLAlertView-Swift.git"
	pod 'FSCalendar', git: "https://github.com/WenchaoIOS/FSCalendar.git"
	pod 'EFCircularSlider', git: "https://github.com/RemyDCF/EFCircularSlider.git"
	pod 'DGRunkeeperSwitch', git: "https://github.com/gontovnik/DGRunkeeperSwitch.git"
end

target "tpg offline Dev" do
pod 'SwiftyJSON', git: "https://github.com/SwiftyJSON/SwiftyJSON.git"
	pod 'ChameleonFramework' , git: "https://github.com/ViccAlexander/Chameleon.git"
	pod 'FontAwesomeKit', git: "https://github.com/PrideChung/FontAwesomeKit.git"
	pod 'SwiftLocation', git: "https://github.com/malcommac/SwiftLocation.git"
	pod 'BGTableViewRowActionWithImage', git: "https://github.com/benguild/BGTableViewRowActionWithImage.git"
	pod 'SCLAlertView', git: "https://github.com/vikmeup/SCLAlertView-Swift.git"
	pod 'FSCalendar', git: "https://github.com/WenchaoIOS/FSCalendar.git"
	pod 'EFCircularSlider', git: "https://github.com/RemyDCF/EFCircularSlider.git"
	pod 'DGRunkeeperSwitch', git: "https://github.com/gontovnik/DGRunkeeperSwitch.git"
end