use_frameworks!

target 'tpg offline' do
pod 'SwiftyJSON'
pod 'ChameleonFramework'
pod 'FontAwesomeKit'
pod 'SwiftLocation'
pod 'BGTableViewRowActionWithImage'
pod 'SCLAlertView'
pod 'FSCalendar'
pod 'EFCircularSlider'
pod 'DGRunkeeperSwitch'
end