# Uncomment this line to define a global platform for your project
platform :osx, '10.11'

target 'tpg offline' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tpg offline
  
  pod 'SwiftyJSON', git: 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'FontAwesomeIconFactory', git: 'https://github.com/nschum/FontAwesomeIconFactory.git'

  target 'tpg offlineUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
